create or replace function nomologies.quarantine_reprocess_candidate()
returns trigger
language plpgsql
security definer
set search_path = nomologies, public
as $$
declare
  attempted_version_id uuid;
  target_version nomologies.case_versions%rowtype;
  target_run nomologies.pipeline_runs%rowtype;
begin
  if old.current_version_id is null
     or new.current_version_id is null
     or new.current_version_id is not distinct from old.current_version_id then
    return new;
  end if;

  -- An explicit human promotion of the already pending candidate is permitted;
  -- the independent regression guards below still determine whether it is safe.
  if old.pending_version_id is not null
     and new.current_version_id = old.pending_version_id then
    return new;
  end if;

  attempted_version_id := new.current_version_id;
  select * into target_version
  from nomologies.case_versions
  where id = attempted_version_id and case_id = old.id;
  if not found or target_version.run_id is null then
    return new;
  end if;

  select * into target_run
  from nomologies.pipeline_runs
  where id = target_version.run_id;
  if not found
     or coalesce(target_run.stage_state #>> '{reprocess,caseId}','') <> old.id::text then
    return new;
  end if;

  -- Any automatic reprocess of an existing case becomes a non-current candidate,
  -- irrespective of whether the current case is published or still under review.
  new := old;
  new.pending_version_id := attempted_version_id;
  new.pending_run_id := target_version.run_id;
  new.pending_readiness_score := target_version.readiness_score;
  new.pending_strict_ready := target_version.strict_ready;
  new.pending_created_at := coalesce(target_version.created_at, now());
  new.human_review_required := true;
  new.updated_at := now();
  return new;
end;
$$;

create or replace function nomologies.guard_case_version_regression_all()
returns trigger
language plpgsql
security definer
set search_path = nomologies, public
as $$
declare
  bypass boolean := coalesce(current_setting('nomologies.allow_engine_recovery',true),'')='on';
  target_version nomologies.case_versions%rowtype;
  previous_version nomologies.case_versions%rowtype;
  target_orchestration text := '';
  target_critical integer := 0;
  previous_critical integer := 0;
  target_ratio integer := 0;
  previous_ratio integer := 0;
  target_obiter integer := 0;
  previous_obiter integer := 0;
  target_secondary integer := 0;
  previous_secondary integer := 0;
  target_tests integer := 0;
  previous_tests integer := 0;
  target_facts integer := 0;
  previous_facts integer := 0;
  target_issues integer := 0;
  previous_issues integer := 0;
  target_holding integer := 0;
  previous_holding integer := 0;
  target_grounds integer := 0;
  previous_grounds integer := 0;
  target_authorities integer := 0;
  previous_authorities integer := 0;
  target_principle integer := 0;
  previous_principle integer := 0;
begin
  if bypass
     or old.current_version_id is null
     or new.current_version_id is null
     or new.current_version_id is not distinct from old.current_version_id then
    return new;
  end if;

  select * into target_version
  from nomologies.case_versions
  where id = new.current_version_id and case_id = new.id;
  select * into previous_version
  from nomologies.case_versions
  where id = old.current_version_id and case_id = old.id;

  if target_version.id is null or previous_version.id is null then
    raise exception using
      errcode='P0001',
      message='INVALID_CASE_VERSION_POINTER',
      detail='The proposed current version or the existing current version does not belong to this case.';
  end if;

  select coalesce(stage_state #>> '{orchestration,version}','')
  into target_orchestration
  from nomologies.pipeline_runs
  where id = target_version.run_id;

  if target_orchestration = 'elite-lean-v2' then
    raise exception using
      errcode='P0001',
      message='ELITE_LEAN_V2_PROMOTION_BLOCKED',
      detail='A candidate generated by the retired lean profile cannot replace any current case version.';
  end if;

  target_critical := coalesce((select count(*) from jsonb_array_elements(coalesce(target_version.conflict_summary->'conflicts','[]'::jsonb)) x where x->>'severity'='critical'),0);
  previous_critical := coalesce((select count(*) from jsonb_array_elements(coalesce(previous_version.conflict_summary->'conflicts','[]'::jsonb)) x where x->>'severity'='critical'),0);

  target_ratio := nomologies.json_field_count(target_version.canonical_record,array['analysis','ratioDecidendi']);
  previous_ratio := nomologies.json_field_count(previous_version.canonical_record,array['analysis','ratioDecidendi']);
  target_obiter := nomologies.json_field_count(target_version.canonical_record,array['analysis','obiterDicta']);
  previous_obiter := nomologies.json_field_count(previous_version.canonical_record,array['analysis','obiterDicta']);
  target_secondary := nomologies.json_field_count(target_version.canonical_record,array['analysis','secondaryPrinciples']);
  previous_secondary := nomologies.json_field_count(previous_version.canonical_record,array['analysis','secondaryPrinciples']);
  target_tests := nomologies.json_field_count(target_version.canonical_record,array['analysis','legalTestsAndStandards']);
  previous_tests := nomologies.json_field_count(previous_version.canonical_record,array['analysis','legalTestsAndStandards']);
  target_facts := nomologies.json_field_count(target_version.canonical_record,array['facts','summary']);
  previous_facts := nomologies.json_field_count(previous_version.canonical_record,array['facts','summary']);
  target_issues := nomologies.json_field_count(target_version.canonical_record,array['analysis','legalIssues']);
  previous_issues := nomologies.json_field_count(previous_version.canonical_record,array['analysis','legalIssues']);
  target_holding := nomologies.json_field_count(target_version.canonical_record,array['analysis','holding']);
  previous_holding := nomologies.json_field_count(previous_version.canonical_record,array['analysis','holding']);
  target_grounds := nomologies.json_field_count(target_version.canonical_record,array['procedure','groundsOrIssues']);
  previous_grounds := nomologies.json_field_count(previous_version.canonical_record,array['procedure','groundsOrIssues']);
  target_authorities := nomologies.json_field_count(target_version.canonical_record,array['authorities','authorities']);
  previous_authorities := nomologies.json_field_count(previous_version.canonical_record,array['authorities','authorities']);
  target_principle := nomologies.json_field_count(target_version.canonical_record,array['analysis','legalPrincipleSummary']);
  previous_principle := nomologies.json_field_count(previous_version.canonical_record,array['analysis','legalPrincipleSummary']);

  if target_version.readiness_score < previous_version.readiness_score
     or target_critical > previous_critical
     or (previous_ratio > 0 and target_ratio = 0)
     or (previous_obiter > 0 and target_obiter = 0)
     or (previous_secondary > 0 and target_secondary = 0)
     or (previous_tests > 0 and target_tests = 0)
     or (previous_facts > 0 and target_facts = 0)
     or (previous_issues > 0 and target_issues = 0)
     or (previous_holding > 0 and target_holding = 0)
     or (previous_grounds > 0 and target_grounds = 0)
     or (previous_authorities > 0 and target_authorities = 0)
     or (previous_principle > 0 and target_principle = 0) then
    raise exception using
      errcode='P0001',
      message='CASE_VERSION_REGRESSION_BLOCKED',
      detail=format(
        'Score %s→%s; critical %s→%s; facts %s→%s; issues %s→%s; holding %s→%s; ratio %s→%s; obiter %s→%s; secondary %s→%s; tests %s→%s; grounds %s→%s; authorities %s→%s; principle %s→%s.',
        previous_version.readiness_score,target_version.readiness_score,
        previous_critical,target_critical,
        previous_facts,target_facts,
        previous_issues,target_issues,
        previous_holding,target_holding,
        previous_ratio,target_ratio,
        previous_obiter,target_obiter,
        previous_secondary,target_secondary,
        previous_tests,target_tests,
        previous_grounds,target_grounds,
        previous_authorities,target_authorities,
        previous_principle,target_principle
      ),
      hint='Keep the candidate pending and compare it field by field. A lower-quality record cannot replace the current version.';
  end if;

  return new;
end;
$$;

drop trigger if exists a_quarantine_reprocess_candidate_trigger on nomologies.cases;
create trigger a_quarantine_reprocess_candidate_trigger
before update of current_version_id on nomologies.cases
for each row execute function nomologies.quarantine_reprocess_candidate();

drop trigger if exists b_guard_case_version_regression_all_trigger on nomologies.cases;
create trigger b_guard_case_version_regression_all_trigger
before update of current_version_id on nomologies.cases
for each row execute function nomologies.guard_case_version_regression_all();

insert into nomologies.system_controls(control_key,enabled,reason,updated_at)
values (
  'reprocess_candidate_quarantine',
  true,
  'Every reprocess of an existing case is stored as a pending candidate; automatic replacement of current review or published records is disabled.',
  now()
)
on conflict (control_key) do update
set enabled=excluded.enabled,reason=excluded.reason,updated_at=excluded.updated_at;

update nomologies.system_controls
set enabled=false,
    reason='Extraction enabled with exact pre-change worker, automatic candidate quarantine and all-status regression protection.',
    updated_at=now()
where control_key='extraction_frozen';
